### Create new order

POST http://localhost:3000/api/orders
Content-Type: application/json

{
 
  "orderItems": [
    {
      "product": "64708f9567e7c9141768dd6e",
      "quantity": 2
    },
    {
      "product": "6470904767e7c9141768dd7a",
      "quantity": 1
    }
  ],
  "deliveryAddress": {
   "firstName": "Madde",
    "lastName": "Gustafsson",
    "address": " 23 gatan",
    "zipCode": "56785",
  "city": "göteborg",
  "phoneNumber": "1234567890"
    
  },
  "isShipped": false
}

### Update shipping status

PUT http://localhost:3000/api/orders/6475c6e304d49fc187ae3760
Content-Type: application/json

{
 "isShipped": true
}

### Get all orders

GET http://localhost:3000/api/orders

### Get orders by user

GET http://localhost:3000/api/orders/gabriel@test.nu


### Get all products

GET http://localhost:3000/api/products

### Log in

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
 "email":"madde@gmail.com",
 "password":"123456789"
}

### Sign out

POST http://localhost:3000/api/users/signout
Content-Type: application/json



