### Create new order

POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "userId": "646ca474c8e83762091ed3ad",
  "orderItems": [
    {
      "product": "646c7a4b63fd50be6e73780b",
      "quantity": 2
    },
    {
      "product": "646c79af63fd50be6e737809",
      "quantity": 1
    }
  ],
  "deliveryAddress": {
    "firstName": "Madde",
    "lastName": "Gustafsson",
    "address": "123 Gatan",
    "zipCode": 12345,
    "city": "Kungälv",
    "phoneNumber": 1234567890
  },
  "isShipped": false
}


### Create new order

PUT http://localhost:3000/api/orders/646b73000217b84af04a4857
Content-Type: application/json

{
  "isShipped": false
}

### Get all orders

GET http://localhost:3000/api/orders